#production:
#  adapter: postgresql
#  encoding: unicode
#  database: foo
#  port: 5432
#  host: foobar.amazonaws.com
#  username: foo
#  password: bar
#

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mylocaldb
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: test_mylocaldb
  pool: 5
  timeout: 5000


